# Generated by Django 6.0.1 on 2026-01-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("INSTRUCTOR", "Instructor"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
