# Generated by Django 5.2.8 on 2026-01-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_user_full_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
