# Generated by Django 5.2.8 on 2026-02-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_question_option_quiz_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATING", "Generating"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                ],
                default="READY",
                max_length=20,
            ),
        ),
    ]
