# Generated by Django 5.2.8 on 2026-02-10 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CallSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caller_id", models.IntegerField(db_index=True)),
                ("callee_id", models.IntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RINGING", "Ringing"),
                            ("ACTIVE", "Active"),
                            ("ENDED", "Ended"),
                            ("MISSED", "Missed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="RINGING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calls",
                        to="chat.chatroom",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
